In [1]:
import numpy as np
import pandas as pd

In [7]:
dados = np.arange(10)
print(dados)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
dados = np.arange(10)
dados = dados.reshape(2,5)
print(dados)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
indice = ['l1','l2','l3','l4','l5','l6','l7','l8','l9','l10']

In [13]:
serie = pd.Series(dados, index=indice)
#print
serie

l1     0
l2     1
l3     2
l4     3
l5     4
l6     5
l7     6
l8     7
l9     8
l10    9
dtype: int32

In [15]:
serie = pd.Series(dados, index = indice)
serie['l3':'l5']

l3    2
l4    3
l5    4
dtype: int32

In [16]:
dados2 = dados.reshape(2,5)
dados2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
tabela = pd.DataFrame(dados2)
tabela

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [20]:
tabela = pd.DataFrame(dados2, index =['l1', 'l2'], columns =['c1', 'c2', 'c3', 'c4', 'c5'] )
tabela

c1  c2  c3  c4  c5
l1   0   1   2   3   4
l2   5   6   7   8   9

In [21]:
np.random.seed(None)
aleatorios = np.random.rand(25).reshape(5,5)
aleatorios

array([[0.90197326, 0.10652614, 0.2017004 , 0.53163764, 0.01439646],
       [0.45571635, 0.02309538, 0.48687194, 0.87750977, 0.30854637],
       [0.23912684, 0.91852491, 0.77454813, 0.89054794, 0.39927764],
       [0.06317983, 0.1969264 , 0.92971246, 0.44385603, 0.66110949],
       [0.75921833, 0.55594348, 0.40169799, 0.14064612, 0.50155683]])

In [25]:
linhas = ['l1','l2','l3','l4','l5']
colunas = ['c1', 'c2', 'c3', 'c4', 'c5'] 

In [27]:
tabela = pd.DataFrame(aleatorios,index=linhas, columns=colunas)
tabela

c1        c2        c3        c4        c5
l1  0.936791  0.626032  0.607110  0.090558  0.685163
l2  0.139597  0.824796  0.121497  0.474384  0.889675
l3  0.440789  0.631421  0.272920  0.198866  0.328780
l4  0.550482  0.038542  0.775236  0.127873  0.387252
l5  0.951907  0.748813  0.883801  0.166613  0.945172

In [28]:
numeros = [1, 2, 4, 9]
for numero in numeros:
    if numero > 5:
        print(numero)

9


In [29]:
tabela  < 0.3

c1     c2     c3     c4     c5
l1  False  False  False   True  False
l2   True  False   True  False  False
l3  False  False   True   True  False
l4  False   True  False   True  False
l5  False  False  False   True  False

In [31]:
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2

c1        c2        c3        c4  c5
l1       NaN       NaN       NaN  0.090558 NaN
l2  0.139597       NaN  0.121497       NaN NaN
l3       NaN       NaN  0.272920  0.198866 NaN
l4       NaN  0.038542       NaN  0.127873 NaN
l5       NaN       NaN       NaN  0.166613 NaN

In [35]:
# substituir número da tabela 
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2['c1']['l2'] = -1
tabela2

c1        c2        c3        c4  c5
l1  NaN       NaN       NaN  0.090558 NaN
l2 -1.0       NaN  0.121497       NaN NaN
l3  NaN       NaN  0.272920  0.198866 NaN
l4  NaN  0.038542       NaN  0.127873 NaN
l5  NaN       NaN       NaN  0.166613 NaN

In [40]:
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2['c1']['l2'] = -1
tabela2

c1        c2        c3        c4  c5
l1  NaN       NaN       NaN  0.090558 NaN
l2 -1.0       NaN  0.121497       NaN NaN
l3  NaN       NaN  0.272920  0.198866 NaN
l4  NaN  0.038542       NaN  0.127873 NaN
l5  NaN       NaN       NaN  0.166613 NaN

In [41]:
tabela2.isnull()

c1     c2     c3     c4    c5
l1   True   True   True  False  True
l2  False   True  False   True  True
l3   True   True  False  False  True
l4   True  False   True  False  True
l5   True   True   True  False  True

In [42]:
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2['c1']['l2'] = -1
tabela2.isna().sum()

c1    4
c2    4
c3    3
c4    1
c5    5
dtype: int64

In [46]:
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2['c1']['l2'] = -1
totaisnan = tabela2.isna().sum()
totaisnan.sum()

17

In [54]:
# Criando as linhas e colunas com alunos,notas e disciplinas
alunos = ['Thyago', 'Theo', 'Sophia']
disciplinas = ['Python', 'Java', 'Banco de Dados']
nan = np.nan
notas = [8.0 ,7.0 , nan, 9.0, 7.5, 10.0, 7.0, nan, 8.0]
notas = np.array(notas)
notas = notas.reshape(3,3)
df = pd.DataFrame(notas, index=alunos, columns=disciplinas)


# Susbistituição das notas nulas  de Java
java = df['Java']
java = java.fillna(java.mean())
df['Java'] = java
df

# Susbistituição das notas nulas  de Banco de Dados
bd = df['Banco de Dados']
bd = bd.fillna(bd.mean())
df['Banco de Dados'] = bd
df

# Criando o filtro de que so mostrar o aluno acima da media em Python
python = df['Python']
filtro = python > python.mean()
print(df[filtro])

      Python  Java  Banco de Dados
Theo     9.0   7.5            10.0
